-- CRIE UMA PROCEDURE CHAMADA INSERE_LOGRADOURO QUE RECEBA COMO PARAMETROS: 
-- DESCRICAO DO LOGRADOURO. 
-- NUMERO LOGRADOURO.
-- NOME DO LOGRADOURO.
-- NOME DA CIDADE.
--
--ESTA PROCEDURO DEVE RETORNAR EM UM PARAMETRO DE SAIDA O CODIGO DO LOGRADOURO QUE FOI GERADO 

CREATE OR REPLACE PROCEDURE INSERE_LOGRADOURO ( 
	DESCRI IN VARCHAR2, 
	NR_LOG IN NUMBER, 
	DS_BAIRRO IN VARCHAR2, 
	DS_CIDADE IN VARCHAR2, 
	COD OUT NUMBER ) IS

DECLARE
CD_BAIRRO NUMBER(7);
NEW_CD_LOG NUMBER(7) 
BEGIN 
	
	--BASEADO NO NOME DO BAIRRO E DA CIDADE DESCOBRIR O COD BAIRRO. 
	--DESCOBRIR O PROXIMO CD_LOG DISPONIVEL.
	--REALIZAR O INSERT.


SELECT MAX(CD_LOGRADOURO) + 1 INTO NEW_CD_LOG FROM LOGRADOUROS
+++++++++++++++++++++++++++++++++++++++++++++++++++++++
SELECT CD_BAIRRO  
INTO  CD_BAIRRO
FROM CIDADES C
INNER JOIN BAIRROS B ON B.CD_CIDADE = C.CD_CIDADE
WHERE DS_CIDADE_NOME = DS_CIDADE
AND DS_NOME_BAIRRO = DS_BAIRRO

INSERT INTO LOGRADOUROS VALUES( NEW_CD_LOG, CD_BAIRRO, , 1, DESCRI);

END;