-- Trabalhando com cursores. 


-- Declarando o cursor 
DECLARE 
CURSOR NOME IS SELECT ALGO FROM TABELA WHERE; 
-- Declarando as variaveis necessarias
VARIAVEL1 TIPO; 
BEGIN 
	-- Abrir o cursor
	OPEN NOME;
	LOOP 
	-- Inserindo valor na variavel e indo para a proxima linha
	FETCH NOME INTO VARIAVEL1;
	EXIT WHEN NOME%NOTFOUND; 
		-- Algum processamento
	END LOOP;  
	-- Fechamento do cursor
	CLOSE NOME; 
END; 


SET SERVEROUTPUT ON;
/

BEGIN 
DBMS_OUTPUT.PUT_LINE('TESTE DE MENSAGEM');
END;
/




DECLARE 
	CURSOR NOME_CIDADES IS SELECT DSCIDADE FROM CIDADE;
	CIDADES VARCHAR2(50);
BEGIN
	OPEN NOME_CIDADES;
	LOOP
	FETCH NOME_CIDADES INTO CIDADES;
	DBMS_OUTPUT.PUT_LINE(CIDADES);
	EXIT WHEN NOME_CIDADES%NOTFOUND;
	END LOOP;
	CLOSE NOME_CIDADES;
END;

-- Curitiba
-- S├úo Paulo
-- Rio de Janeiro
-- Belo Horizonte
-- Jo├úo Pessoa
-- UMACIDADE
-- Foz do Iguaçu
-- Pindamonhangaba
-- Pindamonhangaba



DECLARE 
	CURSOR NOME_CIDADES IS SELECT NOME FROM UF;
	CIDADES VARCHAR2(50);
BEGIN
	OPEN NOME_CIDADES;
	LOOP
	FETCH NOME_CIDADES INTO CIDADES;
	DBMS_OUTPUT.PUT_LINE(CIDADES);
	EXIT WHEN NOME_CIDADES%NOTFOUND;
	END LOOP;
	CLOSE NOME_CIDADES;
END;

-- Acre
-- Alagoas
-- Amazonas
-- Amapá
-- Bahia
-- Ceará
-- Distrito Federal
-- Espírito Santo
-- Goiás
-- Maranhão
-- Minas Gerais
-- Mato Grosso do Sul
-- Mato Grosso
-- Pará
-- Paraíba
-- Pernambuco
-- Piauí
-- Paraná
-- Rio de Janeiro
-- Rio Grande do Norte
-- Rondônia
-- Roraima
-- Rio Grande do Sul
-- Santa Catarina
-- Sergipe
-- São Paulo
-- Tocantins
-- Tocantins



--  CRIE UMA PROCEDURE QUE RECEBA DOIS PARAMETROS,
--  O PRIMEIRO É O NOME DO ESTADO E O SEGUNDO É O NUMERO DE QUANTAS CIDADES SERAO MOSTRADAS

CREATE OR REPLACE PROCEDURE LISTAR_CIDADES (EST IN VARCHAR2, QTD IN NUMBER) IS 
	CURSOR LIST_EST IS SELECT DSCIDADE FROM CIDADE WHERE DSESTADO = EST;
	CIDADES VARCHAR2(50);
BEGIN 
	OPEN LIST_EST;
	FOR I IN 1..QTD LOOP
		FETCH LIST_EST INTO CIDADES;
		DBMS_OUTPUT.PUT_LINE(CIDADES);
		EXIT WHEN LIST_EST%NOTFOUND;
	END LOOP;
	CLOSE LIST_EST;
END;
/


CALL LISTAR_CIDADES('Parana', 1);



-- Tratando as exceptions

DECLARE 
NOME_CIDADES VARCHAR2(50);
BEGIN
	SELECT DSCIDADE
	INTO NOME_CIDADES
	FROM CIDADE;
	DBMS_OUTPUT.PUT_LINE(NOME_CIDADES);
	EXCEPTION WHEN OTHERS THEN NULL;
END;



DECLARE 
NOME_CIDADES VARCHAR2(50);
BEGIN
	SELECT DSCIDADE
	INTO NOME_CIDADES
	FROM CIDADE;
	DBMS_OUTPUT.PUT_LINE(NOME_CIDADES);
	EXCEPTION WHEN TOO_MANY_ROWS THEN DBMS_OUTPUT.PUT_LINE('FODEU');
END;


