DECLARE 
	LINHA VARCHAR(256);
	ARQUIVO UTL_FILE.FILE_TYPE;
BEGIN 
	ARQUIVO := UTL_FILE.FOPEN('log_dir', 'jesus.txt', 'R');
	LINHA := 'Não vai subir ninguem nessa porra!';
	UTL_FILE.PUT_LINE(ARQUIVO, LINHA);
	UTL_FILE.FCLOSE(ARQUIVO);
END;
/

CREATE OR REPLACE DIRECTORY log_dir AS 'C:\temp';


CREATE OR REPLACE FUNCTION FILES(CONTEUDO VARCHAR, ACAO CHAR, DIRETORIO VARCHAR) RETURN BOOLEAN IS 
	DIREC VARCHAR(255);
	ARQUIVO UTL_FILE.FILE_TYPE;
BEGIN 
	IF DIRETORIO = NULL THEN 
		DIREC := 'log_dir';
	ELSE
		DIREC := DIRETORIO;
	END IF;
	ARQUIVO := UTL_FILE.FOPEN(DIREC, 'log_file.txt', ACAO);
	UTL_FILE.PUT_LINE(ARQUIVO, CONTEUDO);
	UTL_FILE.FCLOSE(ARQUIVO);
END;
/
