CREATE PACKAGE NOME AS 

FUNCTION VALIDACPF(CPF NUMBER);
FUNCTION VALIDACNPJ(CNPJ NUMBER);
-- .............

END NOME;

CREATE PACKAGE BODY NOME AS 

-- CÓDIGO DA FUNÇÃO OU PROCEDIMENTO

END NOME;