CREATE OR REPLACE TRIGGER VERIFICACAOCNPJ 
BEFORE INSERT OR UPDATE ON  CLIENTE
FOR EACH ROW 
BEGIN
	IF UTIL.VALIDACNPJ(:NEW.CNPJ_CLIENTE) != 1 THEN 
		RAISE_APPLICATION_ERROR(-20001, 'CNPJ INVÁLIDO');
	END IF;
END;
/


CREATE OR REPLACE TRIGGER VERIFICACAOCPF 
BEFORE INSERT OR UPDATE ON  REPRESENTANTE
FOR EACH ROW 
BEGIN
	IF UTIL.VALIDACPF(:NEW.CPF_REPRESENTANTE) != 1 THEN 
		RAISE_APPLICATION_ERROR(-20001, 'CPF INVÁLIDO');
	END IF;
END;
/

INSERT INTO 
CLIENTE(IDCLIENTE, NOME_CLIENTE, CNPJ_CLIENTE, RAMO_ATIVIDADE, CIDADE, ESTADO, ENDERECO) 
VALUES(1, 'Jose', 17639535000100, 'GAROTO DE PROGRAMA', 'CURITIBA', 'PARANA', 'RUA FREY CANECO');


INSERT INTO 
REPRESENTANTE(IDREPRESENTANTE, NOME_REPRESENTANTE, CPF_REPRESENTANTE) 
VALUES(1, 'Jose', 10615753906);

UPDATE()