

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';


INSERT INTO NOTA_FISCAL(NR_NOTA_FISCAL, IDREPRESENTANTE, IDCLIENTE, DATA_EMISSAO, TIPO_PAGAMENTO) VALUES(1, 1, 1, '06/04/2018', 'CARTAO DEBITO');
INSERT INTO PRODUTO(IDPRODUTO, DSPRODUTO, DSMARCA) VALUES(1, 'STRATOCASTER','FENDER');
INSERT INTO PRODUTOS_NOTA(IDPRODUTO, NR_NOTA_FISCAL, QTD_VENDIDA, VL_UNITARIO, PERC_DESCONTO) VALUES(1, 1, 5, 5.00, 20);
/


SELECT NT.NR_NOTA_FISCAL, CLI.NOME_CLIENTE, NT.DATA_EMISSAO, 
TO_CHAR( (PR.QTD_VENDIDA * PR.VL_UNITARIO) * ( 1 - (PR.PERC_DESCONTO / 100) ) , '09999.99' ) AS TOTAL 
FROM CLIENTE CLI, NOTA_FISCAL NT, PRODUTOS_NOTA PR
WHERE CLI.IDCLIENTE = NT.IDCLIENTE 
AND NT.NR_NOTA_FISCAL = PR.NR_NOTA_FISCAL;


DROP TABLE RELATORIO;


CREATE GLOBAL TEMPORARY TABLE RELATORIO(
	NUMERO_NOTA INTEGER,
	NOME_CLIENTE VARCHAR(150),
	DATA_NOTA DATE, 
	VALOR_NOTA NUMBER(10,2));


CREATE OR REPLACE PROCEDURE GET_TOTAL_NOTA(NR_NOTA_IN IN NOTA_FISCAL.NR_NOTA_FISCAL%TYPE) IS
NR_NOTA_FISCAL NOTA_FISCAL.NR_NOTA_FISCAL%TYPE;
NOME_CLIENTE CLIENTE.NOME_CLIENTE%TYPE; 
DATA_EMISSAO NOTA_FISCAL.DATA_EMISSAO%TYPE;
TOTAL RELATORIO.VALOR_NOTA%TYPE;
BEGIN


SELECT NT.NR_NOTA_FISCAL, CLI.NOME_CLIENTE, NT.DATA_EMISSAO, 
(PR.QTD_VENDIDA * PR.VL_UNITARIO) * ( 1 - (PR.PERC_DESCONTO / 100) ) AS TOTAL 
INTO NR_NOTA_FISCAL, NOME_CLIENTE, DATA_EMISSAO, TOTAL
FROM CLIENTE CLI, NOTA_FISCAL NT, PRODUTOS_NOTA PR
WHERE CLI.IDCLIENTE = NT.IDCLIENTE 
AND NT.NR_NOTA_FISCAL = PR.NR_NOTA_FISCAL
AND NT.NR_NOTA_FISCAL = NR_NOTA_IN;


INSERT INTO RELATORIO(NUMERO_NOTA, NOME_CLIENTE, DATA_NOTA, VALOR_NOTA) 
VALUES(NR_NOTA_FISCAL, NOME_CLIENTE, DATA_EMISSAO, TOTAL);
END;
/